spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/backend
    username: backend
    password: u08/A2oHCi6}
    initialization-mode: never

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    open-in-view: false

  main:
    allow-circular-references: true

  web:
    resources:
      static-locations: file:./uploads

  mvc:
    throw-exception-if-no-handler-found: true

  resources:
    add-mappings: false
  
security:
  jwt:
    secret: 'rb55sfFb2s9sYNoeCLnJSALEK5HkMaTlZLkSoW3kNG3usNl3yGj2aZLrx4ep9EnU'

logging:
  level:
    root: INFO
    com.eticaret.backend: DEBUG
    org.hibernate.SQL: ERROR
    org.hibernate.orm.deprecation: ERROR
    org.hibernate.orm.connections.pooling: ERROR
    org.hibernate.type.descriptor.sql.BasicBinder: ERROR
  file:
    name: logs/backend.log
    